package com.norbu.note.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.joda.time.DateTime;

import java.util.Date;

@DynamoDBTable(tableName="note")
public class Note {

    @DynamoDBHashKey(attributeName = "userId")
    private String userId;



    @DynamoDBRangeKey(attributeName = "noteId")
    @DynamoDBAutoGeneratedKey
    private String noteId;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "body")
    private String body;



    public void setUserId(String userId) {
        this.userId = userId;
    }

    public void setNoteId(String noteId) { this.noteId = noteId;  }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getUserId() {
        return userId;
    }

    public String getNoteId() { return noteId; }

    public String getTitle() {
        return title;
    }

    public String getBody() {
        return body;
    }
    public String toString(){
        return noteId+","+userId+","+title;
    }
}